import = ["/home/nixos/.config/alacritty/wsl_hint.toml", "/home/nixos/.config/alacritty/theme.toml"]

[font]
size = 8.5

[font.bold]
# family = "Cascadia Code"
# style = "Bold"
style = "Bold"

[font.normal]
# family = "Ubuntu Mono"
# family = "Cascadia Code"
style = "Semibold"

[font.offset]
x = 0
y = 2

[hints]
alphabet = "1234567890"

[window.dimensions]
columns = 140
lines = 36
