#!/usr/bin/env bash

ln -s ~/.config/home-manager/config/nvim/ ~/.config/nvim
ln -s ~/.config/home-manager/config/tmux/ ~/.config/tmux/config
ln -s ~/.config/home-manager/config/tmux/tmux.conf ~/.tmux.conf
ln -s ~/.config/home-manager/config/alacritty ~/.config/alacritty
ln -s ~/.config/home-manager/config/ricemood ~/.config/ricemood
ln -s ~/.config/home-manager/config/macchina ~/.config/macchina
ln -s ~/.config/home-manager/config/i3 ~/.config/i3/extra
ln -s ~/.config/home-manager/config/picom ~/.config/picom/extra

ln -s ~/.config/home-manager/config/scripts ~/.scripts

ln -s ~/.config/home-manager/config/fish/completions/ ~/.config/fish/completions
ln -s ~/.config/home-manager/config/fish/conf.d/ ~/.config/fish/conf.d
ln -s ~/.config/home-manager/config/fish/functions/ ~/.config/fish/funcions
