#!/usr/bin/env fish

# new.txt from
#  https://github.com/chrisgrieser/cmp-nerdfont/blob/main/lua/cmp_nerdfont/items.lua
cat ~/.config/home-manager/config/scripts/icons/new.txt | ff | awk '{printf $1;}' | xclip -sel clip
